export const github_user = {
  avatar_url: 'https://avatars.githubusercontent.com/u/19?v=4',
  events_url: 'https://api.github.com/users/brynary/events{/privacy}',
  followers_url: 'https://api.github.com/users/brynary/followers',
  following_url: 'https://api.github.com/users/brynary/following{/other_user}',
  gists_url: 'https://api.github.com/users/brynary/gists{/gist_id}',
  gravatar_id: '',
  html_url: 'https://github.com/brynary',
  id: 19,
  login: 'brynary',
  node_id: 'MDQ6VXNlcjE5',
  organizations_url: 'https://api.github.com/users/brynary/orgs',
  received_events_url: 'https://api.github.com/users/brynary/received_events',
  repos_url: 'https://api.github.com/users/brynary/repos',
  site_admin: false,
  starred_url: 'https://api.github.com/users/brynary/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/brynary/subscriptions',
  type: 'User',
  url: 'https://api.github.com/users/brynary',
};
